### ISSUE TITLE
MapperParsingException[Analyzer [sk_SK] not found for field [text]]

### ISSUE THREAD

**Issue by Pytlicek** [essential-data/elasticsearch-sk#1]
Môj Cluster : 3x (Data + Master) Noda + 1 Noda pre Web
Všade podľa postupu rozbehaný hunspell-sk a reštartovaný celá cluster. 
Pokial som išiel správne podľa návodu vráti mi hlášku o chybe, ze nevie nájsť analyzér :

**Zoznam súborov v adresári :**
[root@Web]# tree /usr/share/elasticsearch/config/
/usr/share/elasticsearch/config/

> hunspell
> 
> > sk_SK
> > 
> > > settings.yml
> > > sk_SK.aff
> > > sk_SK.dic

Index mi vytvorí, aj to mi je divné lebo je v ňom zadefinovaný ten analyzér

**Ale ak chcem urobiť mapping končí chybou :**

curl -XPUT "http://localhost:9200/hunspell/_mapping/tests" -d '{
    "tests": {
        "properties": {
            "text": {
                "type":     "string",
                "analyzer": "sk_SK"
            }
        }
    }
}'
{"error":"RemoteTransportException[[Node2][inet[/10.10.10.4:9300]][indices:admin/mapping/put]]; nested: MapperParsingException[Analyzer [sk_SK] not found for field [text]]; ","status":400}

**Comment by jooray** [comment]
Analyzer treba vytvoriť podľa dokumentácie:

PUT ${ELASTIC_URL}/my_index < examples/create_my_index-asciifolding

**Comment by Pytlicek** [comment]
**Chybu som našiel.** Tá bola na strane nastavení Elasticsearch. v /etc/elasticsearch/elasticsearch.yml som nemal definované "path.conf" a teda bralo default cestu. Preto som ju zadefinoval natvrdo (vlastne na tu istú)  : path.conf: /usr/share/elasticsearch/config

Následne po reštarte ide vytvoriť index aj dokumenty v ňom.
Je len divné, že default cestu nebralo do úvahy, iba ak som ju zadefinoval napevno.
